FROM ubuntu:22.04
RUN apt-get update
RUN apt-get -y install gcc
RUN apt-get -y install g++
RUN apt-get -y install make
RUN apt-get -y install vim
RUN apt-get -y install git
RUN apt-get -y install python3
RUN apt-get -y install default-jdk
RUN apt-get -y install jflex
RUN apt-get -y install ant
RUN apt-get -y install bison flex
RUN apt-get -y install python3-pip
RUN pip3 install ply
RUN pip3 install pytest
RUN apt-get -y install check
RUN apt-get -y install graphviz

